on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: tsc
        run: tsc
      - name: commit transpiled files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Running 'tsc' should not result in changes. Run `tsc` before a commit.";
            exit 1
          fi
      - name: Run tests
        run: yarn test
