on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: yarn install
    - name: tsc
      run: tsc
    - name: commit transpiled files
      run: |
      if [ -n "$(git status --porcelain)" ]; then
        echo "there are changes";
      else
        echo "no changes";
      fi
      